# -*- coding: utf-8 -*-
"""basics.COD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4NwaQ4JiQSKjV-oLysQSFhDVfAbQ97m
"""

#1.length of string
whatif="the world ends today"
print(len(whatif)-len("NOT AT ALL"))

#2.Lists
m=["dune","jaws","VP","titanic","ratatouille"]
print(m[-2][3]+m[-1][-1]+m[-1][-4]+m[4][-6]+m[-5][1])

#3.Dictionary
strength={"it":70,"ece":65,"eee":45,"aiml":50}
strength.update({"cse":64})
print(strength)

#4.
event="easter at april 20"
l=event.split(" ")
print("#".join(l[::-2]))

#5.
name="college of engineering"
print(name[8:11]+"cyc"+name[3]+name[-3:])

#6.
print(float(5+int(4.39+2.1)%2))

#7.
print(3*1**3)

#8.
p,q=8,3
p,q,p=p+1,q+5,p+10
print(p,q)

#9.
print(16//3+3**3+15/4-9)

#10.
t=(2,4,(6,8,(10,12)),14)
print(t[2][2][0]*t[0]+t[-1])

