# -*- coding: utf-8 -*-
"""predict outputs-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bE-1IyaKO_PtpQ2oz7SpjI5tmvNrr0x8
"""

#11.
a = (5,(7,5,(1,2)),5,4)
print(a.count(5))
print(a[1][2])
print(a * 3)
print(len(a))
b = (7,8,(4,5))
print(a + b)

#Q12
x = [3, 6, 9, 12, 15]
y = x[::-1]
print(y[1] + x[-3])

#Q13
word = "Whatever"
print(word[:3] + word[-1] + word[4:2:-1])

#Q14
nums = {3, 6, 9, 12}
nums.add(15)
nums.remove(6)
nums.update([18, 21])
nums.discard(99)
print(sum(nums))

#Q15
info = {"name": "vaishnavi", "age": 18, "state": "T.S"}
info["age"] += 4
info["country"] = "India"
print(info.keys())
print(info.get("state", "Unknown"))

#Q16
num_list = [5, 10, 15, 20, 25]
res = list(map(lambda x: x % 3, num_list))
print(res)

#Q17
ages = [15, 22, 18, 30, 12, 40, 90]
adults = list(filter(lambda x: x >= 18, ages))
print(len(adults))

#Q18
from functools import reduce
nums = [1, 2, 3, 4, 5]
result = reduce(lambda x, y: x * y, nums)
print(result)

#Q19
alpha = ["a", "b", "c", "d"]
print(alpha.pop(2) + alpha[-1])
print(alpha)

#Q20
x = 10
y = 3
x, y = x % y, x // y
print(x)
print(y)